
ARG PY_VERSION

# Use an official Python image as the base image
FROM python:${PY_VERSION}-slim as base

# Set the working directory in the container
WORKDIR /app

RUN if [[ ! "$(python --version)" == "Python 3.6.15" ]]; then \
      pip install 'pip==23.0.1'; \
    else \
      pip install 'pip==21.3.1'; \
    fi

# you should mount the code into /app for the tests to work

# Copy the requirements file to the container
COPY requirements_test.txt setup.py ./
# Install the required packages
RUN touch README.md  # needed for setup.py not to die, but not really used

FROM base as all

RUN pip install -e '.[cli]'
RUN pip install --no-cache-dir -r requirements_test.txt

# Run the tests
CMD [ "./scripts/run_tests_docker.sh" ]

FROM base as no-cli

RUN pip install -e .
RUN pip install --no-cache-dir -r requirements_test.txt

# Run the tests
CMD [ "./scripts/run_tests_docker.sh", "-m", "not cli" ]


